name: Cron

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: clone and mv files
      shell: bash
      run: |
        git clone https://github.com/SAP/abap-file-formats
        pwd
        ls -lG
        ls -lG ../
        ls -lG ../../
        cp abap-file-formats/file-formats/zif_* ../abap-file-format-src/src/
        cp abap-file-formats/file-formats/*/type/zif_* ../abap-file-format-src/src/
        rm -rf abap-file-formats/
    - name: Open PR
      uses: peter-evans/create-pull-request@v4
      with:
        title: Automatic Update
