name: Cron

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: clone and mv files
      uses: action/setup-node@v2
    - name: runs
      run: |
        npm install
        npm run test
        git status
    - name: Open PR
      uses: peter-evans/create-pull-request@v4
      with:
        title: Automatic Update
