name: Cron

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: clone and mv files
      shell: bash
      run: |
        git clone https://github.com/SAP/abap-file-formats $(GITHUB_WORKSPACE)/tmp/
        cd ${GITHUB_WORKSPACE}
        cp tmp/file-formats/zif_* src/
        cp tmp/file-formats/*/type/zif_* src/
        rm -rf tmp/
    - name: Open PR
      uses: peter-evans/create-pull-request@v4
      with:
        title: Automatic Update
