name: Cron

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: clone and mv files
      uses: actions/setup-node@v3
    - name: runs
      run: |
        npm install
        npm run test
        git status
    - name: Open PR
      uses: peter-evans/create-pull-request@v4
      with:
        title: Automatic Update
